// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.184
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MonoTools
{
			static class Vsix
			{
						public const string Id = "694ABA35-6EFE-4AC8-8D8B-0B99867C0720";
						public const string Name = "MonoTools";
						public const string Description = @"MonoTools. Debugging, XBuild, pdb2mdb & MoMA support for Mono in VisualStudio. ";
						public const string Language = "en-US";
						public const string Version = "2.12";
						public const string Author = "johnshope.com";
						public const string Tags = "mono, tools, debugger, remote, xbuild, MoMA, pdb2mdb";
			}
}
